server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /statico/**
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Gisa910515
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings